### ISSUE TITLE
SECURITY ISSUE: You are putting your PRIVATE key in the repo

### ISSUE THREAD

**Issue by karakasa** [AdamWhiteHat/BigDecimal#13]
commit #4b5139f. I think you shouldn't do that.

![image](https://github.com/AdamWhiteHat/BigDecimal/assets/12855165/108a0f5c-e888-46fe-b086-af7283934b07)

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by AdamWhiteHat** [comment]
Oh I know, it feels incredibly wrong to check in a private key, doesnt it?

But yeah, Microsoft recommends it for open source libraries. 🤷

Its a result of the fact that strong naming doesn't provide any of the security guarantees it was originally envisioned to.
