### ISSUE TITLE
Invalid Parse result of negative number in scientific notation

### ISSUE THREAD

**Issue by Degot** [AdamWhiteHat/BigDecimal#15]
Bug: `input = input.Replace(numberFormatProvider.NegativeSign, String.Empty);`

if input starts with NegativeSign, it will replace ALL NegativeSigns in the string.

To Fix: `input = input.Substring(1);`
To Test: `new BigDecimal("-123.123E-20");`

**Comment by AdamWhiteHat** [comment]
Thanks for bringing this to my attention.
This should be fixed now.

Test it out. If you are satisfied with the solution, feel free to close 
the ticket. Otherwise if I don't hear anything from you for a week or two I will probably close it at that point.

**Comment by Degot** [comment]
I've tested fix. It works as expected. Thank you.
