### ISSUE TITLE
Request: round - add support for negative precision

### ISSUE THREAD

**Issue by Bykiev** [AdamWhiteHat/BigDecimal#37]
**Proposal/Summary**
Add support for negative precision to behave like [ROUNDDOWN Excel function](https://support.microsoft.com/en-us/office/rounddown-function-2ec94c73-241f-4b01-8c6f-17e6d7968f53) 

**Rationale**
It will be useful to for rounding down to the left of the decimal point

**Comment by AdamWhiteHat** [comment]
So what you are asking for is 

the functionality of 
=ROUNDDOWN(31415.92654, -2)

Which rounds 31415.92654 down to 2 decimal places to the left of the decimal point, resulting int 31400

By allowing 
`BigDecimal Round(BigDecimal value, Int32 precision) `
to accept negative values on the precision parameter?

**Comment by Bykiev** [comment]
Yes, you're right

**Comment by AdamWhiteHat** [comment]
This is done and should be working.

I have published an updated .nuget version with this feature and all of your bug fixes you have contributed.
nuget

**Comment by Protiguous** [comment]
For any bugs that are noticed, are there tests being written for them also?

**Comment by AdamWhiteHat** [comment]
> For any bugs that are noticed, are there tests being written for them also?

Actually, I did check in tests for this new functionality, just in the commit prior to this one: https://github.com/AdamWhiteHat/BigDecimal/commit/f19fd65a0378ad537d5ff18477cf1478f732462c?diff=split&w=1#diff-8e5528d420d41e964bb8abcb89ae001e61e72506ac2f722a7058d969886e4778R217

**Comment by AdamWhiteHat** [comment]
@Bykiev Are you satisfied here? Can I close this request?

**Comment by Bykiev** [comment]
@AdamWhiteHat , hi, thank you for your inputs. It doesn't seems to be accurate
`val = 88.123459; p = -3;` results to System.ArgumentOutOfRangeException, should be 0

**Comment by AdamWhiteHat** [comment]
> `val = 88.123459; p = -3;` results to System.ArgumentOutOfRangeException, should be 0
Try p = 2.

I wasn't anticipating people trying to pass in a negative precision greater than there are place values to move the decimal point.

But I did just check the actual excel function, and it does seem to accept large negative value than there are digits without error:
![image](https://github.com/AdamWhiteHat/BigDecimal/assets/3144777/eb9f6852-4ccd-4bee-ae14-60d90c78ae7f)


So I guess I will change it to make it match Excel's behavior.

**Comment by AdamWhiteHat** [comment]
A new NuGet package, version 2025.1000.2.122 [is now available](https://www.nuget.org/packages/ExtendedNumerics.BigDecimal/2025.1000.2.122).

**Comment by Bykiev** [comment]
Thank you, works great!
