### ISSUE TITLE
BUG: Version 2025.1000.0.118 dlls are all versioned 0.0.0.0

### ISSUE THREAD

**Issue by ristogod** [AdamWhiteHat/BigDecimal#43]
**Description**

**Error/Exception Message**
We updated to the latest package from nuget.org which is 2025.1000.0.118. This caused lots of issues with binding redirects in app.config/web.config files in legacy applications. Visual Studio set them all to

``` xml
<dependentAssembly>
    <assemblyIdentity name="ExtendedNumerics.BigDecimal" culture="neutral" publicKeyToken="65f1315a45ad8949" />
    <bindingRedirect oldVersion="0.0.0.0-0.0.0.0" newVersion="0.0.0.0" />
</dependentAssembly>
```

**Expected Behavior**
Dlls in package should be version 2025.1000.0.118

**Actual Behavior**
Dlls in package are versioned 0.0.0.0

**Steps To Reproduce**
Use a package explorer or JetBrains dotPeek to inspect the package. Open any dll listed and they all state 0.0.0.0 as their version.

**Screenshots**
![image](https://github.com/AdamWhiteHat/BigDecimal/assets/13905338/3e6a37e7-2c48-4d75-b016-62ccf057895d)

**Comment by AdamWhiteHat** [comment]
Big yikes.
Sorry about that.
I have remedied this problem. Try upgrading to [NuGet version 2025.1000.1.121](https://www.nuget.org/packages/ExtendedNumerics.BigDecimal/2025.1000.1.121)

**Comment by AdamWhiteHat** [comment]
If you're satisfied that the issue has been resolved, feel free to close the ticket.
Or do nothing at all and I will close the ticket in a day or two.

**Comment by ristogod** [comment]
thanks
