### ISSUE TITLE
Is it possible, that you submit your code to the .NET runtime ?

### ISSUE THREAD

**Issue by theuserbl** [AdamWhiteHat/BigDecimal#47]
Is it possible, that you could add your code to the .NET Runtime ?
https://github.com/dotnet/runtime

I think it could find place in this directories
https://github.com/dotnet/runtime/tree/af11dbc1a34538d9a38d39a7c96ddd5e7fc6907b/src/libraries/System.Runtime.Numerics/src/System/Numerics
https://github.com/dotnet/runtime/tree/af11dbc1a34538d9a38d39a7c96ddd5e7fc6907b/src/libraries/System.Private.CoreLib/src/System

Then anybody can direct using it.
And possible PowerShell would then supporting it, too. So that it is possible to calculate direct on command line with big decimal.
So that beside
`[math]::pow(15,3)`
and
`[bigint]::pow(15324,343)`
also exists for PowerShell
`[bigdec]::pow(153.24,34.3)`
for example. 🙂

**Comment by AdamWhiteHat** [comment]
Gee, wouldn't that be nice? 
Id be honored to have a library I wrote incorporated into the .NET framework.

I don't know for certain how things like this go, but I suspect they don't start by the owner of a library advocating for its inclusion into the framework,

but rather by having a useful and popular library, having a permissive license and one day a Microsoft employee looking for an already-made solution to a current problem using your library, and then that feature becoming integral to the framework.


At any rate, I mentioned how to use this library assembly in PowerShell [here in the new documentation wiki I just wrote](https://github.com/AdamWhiteHat/BigDecimal/wiki/Documentation#using-in-powershell). Several of the headings based on conversations we have recently had here.
