### ISSUE TITLE
Nice demo program

### ISSUE THREAD

**Issue by theuserbl** [AdamWhiteHat/BigDecimal#48]
A nice demo program like at
https://github.com/c-ohle/RationalNumerics
the there shown calculator would be nice.
One program, which demonstrates the complete functionality.
(btw: in that calculator of the mentioned link, the num-pad the key-positiones are mirrored. So would be nice, with a better one)

**Comment by AdamWhiteHat** [comment]
Yeah, this is a good idea. I will try and add something like this in the future.
I'm also looking at producing a graphic or logo for the project, where the design or what's show in the image required the use of arbitrarily large floating point numbers.

Imma close this for now, but its definitely on my radar. Feel free to submit a pull request if you ever create such a project.
