### ISSUE TITLE
ISSUE: Warning NETSDK1138: Out of support frameworks.

### ISSUE THREAD

**Issue by Protiguous** [AdamWhiteHat/BigDecimal#51]
**Description**

- The target framework 'netcoreapp3.1' is out of support and will not receive security updates in the future.
- The target framework 'net5.0' is out of support and will not receive security updates in the future.

**Error/Exception Message**

- Warning NETSDK1138: The target framework 'netcoreapp3.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
- Warning NETSDK1138: The target framework 'net5.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.

**Comment by AdamWhiteHat** [comment]
Yup, this is fine. This is just a warning letting you know the target framework will no longer be updated/is no longer maintained from a code-wise standpoint. I will be reviewing which target frameworks we support in the future, with an eye to shortening that list (makes for a smaller .NuGet package--less binaries). I hope to gather some statistics/data around framework usage numbers to help inform this.
