### ISSUE TITLE
BUG: BigDecimal.Truncate should not call BigDecimal.Floor

### ISSUE THREAD

**Issue by Joy-less** [AdamWhiteHat/BigDecimal#53]
**Description**
The implementation mistakenly assumes and claims truncation is the same as flooring (rounding down). However, there is a difference if the number is negative.

**Expected Behavior**
Negative numbers are truncated.

**Actual Behavior**
Negative numbers are rounded down.

**Steps To Reproduce**
```cs
Console.WriteLine(BigDecimal.Truncate(new BigDecimal(-15.5))); // -16 (should be -15)
Console.WriteLine(BigDecimal.Floor(new BigDecimal(-15.5))); // -16

Console.WriteLine(Math.Truncate(-15.5)); // -15
Console.WriteLine(Math.Floor(-15.5)); // -16
```

**Additional context/Comments/Notes/Rants**
Both of these could have instance methods.

**Comment by AdamWhiteHat** [comment]
Good catch. Thanks for bringing this to my attention.
I have fixed this, and this fix is included in NuGet package version [2025.1003.0.225](https://www.nuget.org/packages/ExtendedNumerics.BigDecimal/2025.1003.0.225) or just pull the latest changes from the main branch.
