### ISSUE TITLE
Question: Rounding behaviour

### ISSUE THREAD

**Issue by wolframhaussig** [AdamWhiteHat/BigDecimal#56]
Currently, there are 3 options for rounding:
- use `Round(7.9)` or `Round(7.9, MidpointRounding.AwayFromZero)` to round to the nearest integral value
- use `Round(7.95, 1)` to round to an arbitrary number of decimal places

I have 2 issues with the last one:
- Although it is stated in the docs that `mimics Excel's ROUNDDOWN function` this is not reflected in the method name. I searched a while for the error why it didn't round up to 8.
- There is no method that rounds to an arbitrary number of decimal places while honouring the mathematical rounding rules

I am sure that you do not want breaking changes, so maybe there could be a new `Round(7.9, MidpointRounding.AwayFromZero, 2)` for rounding?
Maybe you could add a `RoundDown(7.95, 1)` function and deprecate the old one to make the behaviour apparent in the method name?

**Comment by AdamWhiteHat** [comment]
Ah, hmm, yes.. I agree, there needs to be a Rounding overload that takes a precision parameter and a MidpointRounding enum.
In fact, I was rather surprised that this was missing.

Note, I intend to give it the signature:
`public static BigDecimal Round(BigDecimal value, int precision, MidpointRounding roundingMode)` 
so it is analogous to the .NET Framework's Math.Round method. (This differs from the example you gave, in the ordering of the parameters).
 
I also like your suggestion of using the method name RoundDown to signify that it is analogous to Excel's ROUNDDOWN function. 
I might not make this breaking change right away; I have another breaking change that needs to get published, and so I will probably document the breaking changes really well and push them out together.

I will probably work on this tonight, as I have to attend to work coding stuff right now, and naturally, the client wants it yesterday.

I just wanted to acknowledge this so you know I've seen it and intend to add this.

**Comment by AdamWhiteHat** [comment]
This is done. You can start using these changes right away by downloading the [NuGet package version 2025.1004.0.247](https://www.nuget.org/packages/ExtendedNumerics.BigDecimal/2025.1004.0.247).

You'll notice it takes as a parameter its own custom enum, not the System.MidpointRounding enum. This is because MidpointRounding.ToZero does not exist in every version of .NET that we support.
