### ISSUE TITLE
BUG: Rare incorrect modulo result

### ISSUE THREAD

**Issue by Joy-less** [AdamWhiteHat/BigDecimal#61]
**Description**
I stumbled upon a random case where the modulo (%) operator doesn't work correctly.
```cs
ExtendedNumerics.BigDecimal Number = -157766400;
Console.WriteLine(Number % 60);
Console.ReadLine(); // 60 (incorrect)
```
```cs
System.Numerics.BigInteger Number = -157766400;
Console.WriteLine(Number % 60);
Console.ReadLine(); // 0 (correct)
```
```cs
float Number = -157766400;
Console.WriteLine(Number % 60);
Console.ReadLine(); // -0 (correct)
```

Changing it from `-157766400` to `157766400`, `-120`, `120` all correctly give 0.

**Expected Behavior**
It should return 0 if modulo by an exact divisor.

**Actual Behavior**
It returns the divisor.

**Version**
ExtendedNumerics.BigDecimal.3000.0.0.280

**Comment by AdamWhiteHat** [comment]
So I tracked down the issue. Strangely, this is happening because there is a  bug in BigDecimal.Floor, where the result is off by +1 when the  parameter is negative.
I will issue probably before the end of the weekend.

**Comment by Protiguous** [comment]
I'm creating a pull request right now.
Please double-check the altered code in the Mod() and Floor() functions.

**Comment by Protiguous** [comment]
Pull request created.

**Comment by AdamWhiteHat** [comment]
@Joy-less This should be fixed now.

New NuGet package release here: [ExtendedNumerics.BigDecimal/3000.0.1.312](https://www.nuget.org/packages/ExtendedNumerics.BigDecimal/3000.0.1.312)

@Protiguous Bah! Sorry, I didn't see your PR until after I had already pushed a commit. Thanks for stepping in and submitting a fix   when I did not issue a fix right away. I appreciate it.
