### ISSUE TITLE
Minor issue: "nu5035" after a Publish.

### ISSUE THREAD

**Issue by Protiguous** [AdamWhiteHat/BigDecimal#9]
**Description**
I'm seeing the message, "**The PackageLicenseUrl is being deprecated and cannot be used in conjunction with the PackageLicenseFile or PackageLicenseExpression.**" when I attempt to "Publish" to a local folder.

The source I'm using is over at: [Protiguous - BigDecimal, experimental branch](https://github.com/Protiguous/BigDecimal/tree/experimental)

**Steps To Reproduce**
Just tried a **Publish** to a temp folder on my machine while under the "Release" mode.

**Additional Comments**
Is this a real "issue"? Maybe something you know how to fix?
All I could find was at, "[Microsoft Docs nu5035](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5035)" and slightly less at "[Nuget Reference](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)".

**Comment by Protiguous** [comment]
Hah, I just compared your commits against my branch and one of the first todo is this!

Okay, I'll see if I can find where to remove it..

**Comment by Protiguous** [comment]
Found it. Removed it. Pushed it.

**Comment by AdamWhiteHat** [comment]
Ah, looks like you found it. Yeah, I'm using the the PackageLicenseExpression node now, because I was getting tired of seeing a warning that the PackageLicenseUrl was being deprecated.
